// Miscellaneous

NTSYSAPI ULONG NTAPI RtlRandomEx(IN OUT PULONG Seed);

HANDLE StdIn=INVALID_HANDLE_VALUE;
HANDLE StdOut=INVALID_HANDLE_VALUE;

HANDLE GuestStdInPipe=INVALID_HANDLE_VALUE;
HANDLE GuestStdOutPipe=INVALID_HANDLE_VALUE;
HANDLE GuestStdErrPipe=INVALID_HANDLE_VALUE;
BOOL ConsoleProcessCreated=FALSE;
PROCESS_INFORMATION ConsoleProcess={0};