// Main header.

HANDLE StdIn=INVALID_HANDLE_VALUE;
HANDLE StdOut=INVALID_HANDLE_VALUE;
HANDLE StdErr=INVALID_HANDLE_VALUE;

HANDLE GuestStdInPipe=INVALID_HANDLE_VALUE;
HANDLE GuestStdOutPipe=INVALID_HANDLE_VALUE;
HANDLE GuestStdErrPipe=INVALID_HANDLE_VALUE;